# Generated by Django 5.1.5 on 2025-01-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
